/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controller;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.benh;
import model.tamQuanTrongXungBenh;

/**
 *
 * @author Admin
 */
public class chonTamQuanTrongGUI extends javax.swing.JFrame {
    private controller ctrl ;
    
    /**
     * Creates new form chonTamQuanTrong
     */
    public chonTamQuanTrongGUI(controller viewCtrl) {
        initComponents();
        this.ctrl = viewCtrl;
        List<tamQuanTrongXungBenh> importantness = new ArrayList<>();
        importantness.addAll(ctrl.gettamQuanTrongs());
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      
        for(int i = 0;i < importantness.size(); i++) {
         model.addRow(new Object[0]);
         model.setValueAt(importantness.get(i).getBenh().getTenBenh(), i, 0);
         model.setValueAt(importantness.get(i).getXung().getTenXung(), i, 1);
         model.setValueAt(importantness.get(i).getGiaTri(), i, 2);

         String cacTrieuChung = "";
         for( benh benh : ctrl.getBenhs()){
             cacTrieuChung += benh.getTenBenh()+", ";
         }
         cacTrieuchungLb.setText(cacTrieuChung);
        jTable1.setEnabled(false);
        jTable1.setBackground(Color.LIGHT_GRAY);
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        setImportantLvlComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        startCalcBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cacTrieuchungLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Triệu chứng", "Xung", "Tầm quan trọng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lựa chọn tầm quan trọng");

        returnBtn.setText("Quay lại");
        returnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBtnMouseClicked(evt);
            }
        });

        setImportantLvlComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Như nhau", "Khác nhau" }));
        setImportantLvlComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setImportantLvlComboBoxItemStateChanged(evt);
            }
        });

        jLabel2.setText("Chọn mức độ quan trọng");

        startCalcBtn.setText("Bắt đầu tính toán");
        startCalcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startCalcBtnMouseClicked(evt);
            }
        });
        startCalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCalcBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Các triệu chứng có thể có: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cacTrieuchungLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setImportantLvlComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startCalcBtn)
                                .addGap(50, 50, 50)
                                .addComponent(returnBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cacTrieuchungLb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(setImportantLvlComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startCalcBtn)
                    .addComponent(returnBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startCalcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startCalcBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startCalcBtnActionPerformed

    private void returnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ctrl.getNhapXung().setVisible(true);
    }//GEN-LAST:event_returnBtnMouseClicked

    private void startCalcBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startCalcBtnMouseClicked
        // TODO add your handling code here:
        if(setImportantLvlComboBox.getSelectedIndex() == 0){
            
        }else{
            
        }
        
        this.setVisible(false);
        ctrl.setImportantLvl(this);
        ctrl.showKetQuaGUI(ctrl);
        
    }//GEN-LAST:event_startCalcBtnMouseClicked

    private void setImportantLvlComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setImportantLvlComboBoxItemStateChanged
        
       if (evt.getStateChange() == ItemEvent.SELECTED) {
          Object item = evt.getItem();
          // do something with object
           System.out.println(item);
           if("Như nhau".equals((String)item)){
               jTable1.setEnabled(false);
               jTable1.setBackground(Color.LIGHT_GRAY);
           }else{
               jTable1.setBackground(Color.WHITE);
           }
          
          
       }
       
    }//GEN-LAST:event_setImportantLvlComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chonTamQuanTrongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chonTamQuanTrongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chonTamQuanTrongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chonTamQuanTrongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new chonTamQuanTrongGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel cacTrieuchungLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton returnBtn;
    private javax.swing.JComboBox<String> setImportantLvlComboBox;
    private javax.swing.JButton startCalcBtn;
    // End of variables declaration//GEN-END:variables
}
